# Problem -1

## Make 15 samples, each sample will contain 10 classes(Age, Marks, height, etc.) and each class contain 20 entries (which we generate using random function generator). 

### Now calculate the mean and variance of each sample class.
### And calculate the mean and variance for whole (200 entries) means for each sample.

### Step -1

#Create 15 samples
Number of samples - S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S15 

Each sample will contain 10 class and each class will contain 20 entries.

In [22]:
import numpy as np
import random

In [23]:
age = np.random.randint(18,25,20) 
marks = np.random.randint(30, 100, 20) 
height = np.random.randint(130, 190, 20)
weight = np.random.randint(35, 105, 20) 
iq = np.random.randint(80,130, 20)
studyhr = np.random.randint(0,12, 20)
sleephr = np.random.randint(4, 12, 20)
prevmarks = np.random.randint(30, 100, 20)
subjects = np.random.randint(1,6, 20)
grescore = np.random.randint(130,170, 20)

s1 = [age, marks, height, weight, iq, studyhr, sleephr, prevmarks, subjects, grescore]

In [24]:
s1

[array([22, 21, 20, 20, 20, 24, 20, 24, 24, 20, 18, 20, 19, 24, 23, 20, 24,
        21, 23, 18]),
 array([70, 99, 35, 37, 67, 63, 57, 81, 60, 73, 76, 39, 97, 33, 97, 84, 93,
        58, 67, 94]),
 array([167, 159, 148, 144, 169, 136, 158, 182, 140, 162, 176, 189, 159,
        148, 166, 159, 186, 169, 158, 184]),
 array([64, 90, 62, 95, 47, 52, 42, 91, 86, 67, 97, 86, 65, 57, 40, 57, 57,
        53, 64, 53]),
 array([111, 129, 114,  99, 109, 125, 123, 102,  95,  87, 128, 108,  99,
        107, 123,  99,  95,  86, 104, 102]),
 array([11,  5,  1,  3,  2,  6,  3, 10,  6,  7,  2,  8,  0,  1, 11,  8,  6,
         0,  0,  1]),
 array([ 6, 11, 11,  8, 10,  8,  6,  4,  5,  4,  4,  9, 10,  6, 10,  9,  8,
         7,  4, 10]),
 array([48, 41, 41, 82, 98, 75, 94, 70, 37, 37, 63, 88, 37, 64, 34, 35, 91,
        80, 75, 51]),
 array([3, 5, 5, 2, 2, 2, 2, 5, 4, 5, 2, 2, 2, 3, 5, 4, 3, 4, 4, 3]),
 array([133, 162, 140, 162, 163, 135, 130, 167, 138, 154, 146, 162, 162,
        154, 151, 157, 165, 134, 

# Calculate the mean and variance for each class of S1

# Mean 

$ \mu = \frac{1}{N} (\sum \limits_{i=1}^N X_{i})$

In [48]:
def mean(x):
    return (sum(x)/len(x))

In [56]:
age_mean = mean(age)
age_mean

21.25

# Variance
$\sigma ^2 = \frac{1}{N} ( \sum \limits_{i=1}^N (X_{i} - \mu)^2)$

In [53]:
def variance(x, mu):                              
    dev = [(i-mu)**2 for i in x]
    var = mean(dev)
    return(var)

In [58]:
age_var = variance(age, age_mean)
age_var

4.0875

In [60]:
marks_mean = mean(marks)
marks_var = variance(marks, marks_mean)
marks_mean, marks_var

(69.0, 443.5)

In [61]:
height_mean = mean(height)
height_var = variance(height, height_mean)
print(height_mean, height_var)

162.95 222.04750000000004


In [62]:
weight_mean = mean(weight)
weight_var = variance(weight, weight_mean)
weight_mean, weight_var

(66.25, 310.8875)

In [64]:
iq_mean = mean(iq)
iq_var = variance(iq, iq_mean)
iq_mean, iq_var

(107.25, 160.4875)

In [65]:
studyhr_mean = mean(studyhr)
studyhr_var = variance(studyhr, studyhr_mean)
studyhr_mean, studyhr_var

(4.55, 13.347499999999997)

## Mean and Variance of whole class data of sample S1

In [99]:
allnum = np.append(age, marks)
allnum = np.append(allnum, height)
allnum = np.append(allnum, weight)
allnum = np.append(allnum,iq)
allnum = np.append(allnum, studyhr)
allnum = np.append(allnum, sleephr)
allnum = np.append(allnum, prevmarks)
allnum = np.append(allnum,subjects)
allnum = np.append(allnum, grescore)

In [100]:
len(allnum)

200

In [101]:
allnum

array([ 22,  21,  20,  20,  20,  24,  20,  24,  24,  20,  18,  20,  19,
        24,  23,  20,  24,  21,  23,  18,  70,  99,  35,  37,  67,  63,
        57,  81,  60,  73,  76,  39,  97,  33,  97,  84,  93,  58,  67,
        94, 167, 159, 148, 144, 169, 136, 158, 182, 140, 162, 176, 189,
       159, 148, 166, 159, 186, 169, 158, 184,  64,  90,  62,  95,  47,
        52,  42,  91,  86,  67,  97,  86,  65,  57,  40,  57,  57,  53,
        64,  53, 111, 129, 114,  99, 109, 125, 123, 102,  95,  87, 128,
       108,  99, 107, 123,  99,  95,  86, 104, 102,  11,   5,   1,   3,
         2,   6,   3,  10,   6,   7,   2,   8,   0,   1,  11,   8,   6,
         0,   0,   1,   6,  11,  11,   8,  10,   8,   6,   4,   5,   4,
         4,   9,  10,   6,  10,   9,   8,   7,   4,  10,  48,  41,  41,
        82,  98,  75,  94,  70,  37,  37,  63,  88,  37,  64,  34,  35,
        91,  80,  75,  51,   3,   5,   5,   2,   2,   2,   2,   5,   4,
         5,   2,   2,   2,   3,   5,   4,   3,   4,   4,   3, 13

In [102]:
allnum_mean = mean(allnum)
allnum_var = variance(allnum, allnum_mean)
allnum_mean, allnum_var

(65.57, 3335.1951000000013)